# Generated by Django 5.1.15 on 2026-10-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim')),
            ],
            options={
                'verbose_name': 'Pesan masuk',
                'verbose_name_plural': 'Pesan masuk',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Lazareth', max_length=120, verbose_name='Nama lengkap')),
                ('headline', models.CharField(default='Software Engineer — Django & Web Development', max_length=200, verbose_name='Headline')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Foto profil')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Judul')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Gambar')),
                ('tech_stack', models.CharField(blank=True, help_text='Pisahkan dengan koma: Django, PostgreSQL, Docker', max_length=250, verbose_name='Tech stack')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repository URL')),
                ('demo_url', models.URLField(blank=True, verbose_name='Live demo URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Tampilkan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nama skill')),
                ('level', models.CharField(blank=True, help_text='Mis. Advanced / Intermediate', max_length=40, verbose_name='Level')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skill',
                'ordering': ['order', 'name'],
            },
        ),
    ]
