# Generated by Django 5.2.18 on 2026-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Portofolio', max_length=120, verbose_name='Nama lengkap'),
        ),
    ]
